fix(hmr-externals): wip
americanexpress/one-app-cli pull request #413
Opened 2021-11-10 17:20 UTC by JAdshead

#### Provide a general summary of your changes in the Title above.

## **Description**
#### _Describe your changes in detail_

#### _This project only accepts pull requests related to open issues._
#### _If suggesting a new feature or change, please discuss it in an issue first._

## **Motivation** 
#### _Why is this change required? What issue does it resolve?_

## **Test** **Conditions**
#### _Describe in detail how the changes are tested._ 
#### _Include details of your testing environment, and the tests you ran to._
#### _How does your change affect the rest of the code._ 

## **Types of changes**
#### Check boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## **Checklist**
#### Check boxes that apply:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] I have added the Apache 2.0 license header to any new files created.

2021-11-12 16:20 UTC, Matthew-Mallimo approved these changes

2021-11-12 17:41 UTC, 10xLaCroixDrinker requested changes

2021-11-12 17:41 UTC, 10xLaCroixDrinker commented on packages/holocron-dev-server/__tests__/src/webpack/loaders/holocron-webpack-loader.spec.js
> +// import { getOptions } from 'loader-utils';
```suggestion
```

2021-11-12 17:59 UTC, 10xLaCroixDrinker approved these changes

2021-11-12 18:57 UTC, 10xLaCroixDrinker approved these changes

2021-11-15 16:37 UTC, Matthew-Mallimo approved these changes

2021-11-15 20:12 UTC, merged