fix(hash): use OpenSSL supported hash for webpack
americanexpress/one-app-cli pull request #488
Opened 2022-12-16 16:21 UTC by Matthew-Mallimo

This is needed for Node 17 and greater, otherwise the --openssl-legacy-provider flag is required.

## **Description**
#### _Describe your changes in detail_
Node.js v17 included OpenSSL 3.0 support, which removed support for certain crypto algorithms like `md4`. `md4` is the default for Webpack 4. This change introduces a monkey patch to use sha256 instead. 
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V17.md#openssl-30

2022-12-16 17:08 UTC, giulianok submitted a review, later dismissed

2022-12-16 17:23 UTC, dogpatch626 submitted a review, later dismissed

2022-12-16 21:38 UTC, bishnubista approved these changes

2022-12-20 17:56 UTC, 10xLaCroixDrinker requested changes

2022-12-20 17:56 UTC, 10xLaCroixDrinker commented on packages/one-app-bundler/__tests__/webpack/app/webpack.client.spec.js
> +    crypto.createHash = mockHash;
Instead of overwriting in the tests, can you use a spy?

2023-01-03 15:18 UTC, giulianok approved these changes

2023-01-03 18:21 UTC, dogpatch626 approved these changes

2023-01-04 04:22 UTC, 10xLaCroixDrinker approved these changes

2023-01-04 04:23 UTC, merged