fix(dev-bundler): skip plugins when no results metadata
americanexpress/one-app-cli pull request #513
Opened 2023-04-04 21:00 UTC by smackfu

## **Description**
Do not run the `onEnd` plugins when the results metadata is not defined.

Fixes #512 

## **Motivation** 

When the build fails due to a syntax error or similar, the `onEnd` plugins are called with a results object that does not have a `metadata` key.  Most of the plugins have reference to `result.metafile.outputs` so they themselves throw an error, which thoroughly obscures the original syntax error.

## **Test** **Conditions**

Unit tests plus ran changes locally.  Output shows only the two relevant failures, rather than pages of stack traces.
```
* $ npm run watch:build

> package@1.0.0 watch:build
> bundle-module --dev --watch

Running dev bundler
Generated language packs for en-US
Watching...
✘ [ERROR] Could not resolve "./Dynamic Table"

    src/components/history/History.jsx:9:39:
      9 │ import DynamicTable from './Dynamic Table';
        ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./Dynamic Table"

    src/components/history/History.jsx:9:39:
      9 │ import DynamicTable from './Dynamic Table';
        ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Server bundle failed, see above for reason
Browser bundle failed, see above for reason
Browser bundle built in 1068ms
Server bundle built in 1087ms
```

## **Types of changes**
#### Check boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## **Checklist**
#### Check boxes that apply:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] I have added the Apache 2.0 license header to any new files created.

2023-04-05 22:47 UTC, JAdshead submitted a review, later dismissed

2023-04-05 22:56 UTC, 10xLaCroixDrinker requested changes

2023-04-05 22:56 UTC, 10xLaCroixDrinker commented on packages/one-app-dev-bundler/__tests__/esbuild/plugins/cjs-compatibility-hotpatch.spec.js
> +      expect(fs.promises.writeFile).toHaveBeenCalledTimes(0);
```suggestion
      expect(fs.promises.readFile).not.toHaveBeenCalled();
      expect(fs.promises.writeFile).not.toHaveBeenCalled();
```

2023-04-05 22:56 UTC, 10xLaCroixDrinker commented on packages/one-app-dev-bundler/__tests__/esbuild/plugins/generate-integrity-manifest.spec.js
> +        expect(fs.promises.writeFile).toHaveBeenCalledTimes(0);
```suggestion
        expect(fs.promises.readFile).not.toHaveBeenCalled();
        expect(fs.promises.writeFile).not.toHaveBeenCalled();
```

2023-04-07 19:50 UTC, Matthew-Mallimo approved these changes

2023-04-07 19:51 UTC, Matthew-Mallimo approved these changes

2023-04-07 19:52 UTC, PixnBits commented
> Most of the plugins have reference to `result.metafile.outputs` so they themselves throw an error, which thoroughly obscures the original syntax error.

Adding to the fun of tracking this down. Great find, thank you!

> Output shows only the two relevant failures, rather than pages of stack traces.

🚀

2023-04-07 19:52 UTC, PixnBits approved these changes

2023-04-07 19:57 UTC, merged