chore(release): publish packages
americanexpress/one-app-cli pull request #546
Opened 2023-06-13 21:14 UTC by dogpatch626

- @americanexpress/holocron-dev-server@0.1.14
 - @americanexpress/one-app-bundler@6.20.0
 - @americanexpress/one-app-dev-bundler@1.4.2
 - @americanexpress/one-app-locale-bundler@6.5.11
 - @americanexpress/one-app-runner@6.14.7

#### Provide a general summary of your changes in the Title above.

## @americanexpress/one-app-bundler
### Features
* **purgecss:** allow for backwards compatibility of purgecss 2 and 3 ([#519](https://github.com/americanexpress/one-app-cli/issues/519)) ([3ab7d58](https://github.com/americanexpress/one-app-cli/commit/3ab7d583957b02093868c104137a90f4a3e27242))

## @americanexpress/one-app-dev-bundler 
### Bug Fixes
* **dev-bundler:** improve error when NODE_ENV not development ([#528](https://github.com/americanexpress/one-app-cli/issues/528)) ([e1babee](https://github.com/americanexpress/one-app-cli/commit/e1babeed1ddc3f0e41f49850e9eb74bf494d0aa9))
* **one-app-dev-bundler:** avoid default export of sass ([0d9b5b4](https://github.com/americanexpress/one-app-cli/commit/0d9b5b422a9e18cc6391fa119abe41b7d384c154))

## @americanexpress/one-app-runner
### Bug Fixes
* **one-app-runner-test:** improve console messaging ([#526](https://github.com/americanexpress/one-app-cli/issues/526)) ([900add5](https://github.com/americanexpress/one-app-cli/commit/900add571d48ad578726bc03bf38d2101eae2590))
* **one-app-runner:** one-app-runner print startup error messages ([#538](https://github.com/americanexpress/one-app-cli/issues/538)) ([548e954](https://github.com/americanexpress/one-app-cli/commit/548e95418778c9ea8785f9ae099c62dc517cb13b))

2023-06-13 21:20 UTC, PixnBits approved these changes

2023-06-13 21:20 UTC, smackfu commented
@dogpatch626 while I appreciate the thanks, those commits were in the previous release, so looks like something is messed up with the tags again. :(

For example, this is skipping 0.1.13:
> ## [0.1.14](https://github.com/americanexpress/one-app-cli/compare/@americanexpress/holocron-dev-server@0.1.12...@americanexpress/holocron-dev-server@0.1.14) (2023-06-13)

2023-06-13 21:23 UTC, Matthew-Mallimo approved these changes

2023-06-13 21:24 UTC, Matthew-Mallimo requested changes
scotts comments

2023-06-13 21:26 UTC, closed without merging

2023-06-14 18:12 UTC, PixnBits commented
🐢 , but replaced with #547